name: bookie
version: '0.1.1'
author: Scott Murphy <scottmurphy09@gmail.com>
maintainer: Scott Murphy <scottmurphy09@gmail.com>
license: BSD3
dependencies:  
  - aeson
  - base
  - bytestring
  - directory
  - either
  - lens
  - lens-regex
  - optparse-generic
  - process  
  - regex-base
  - regex-posix
  - shake
  - text
  - yaml
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
    - Project.Defaults
    - Project.Execute
    - Project.Initialize
    - Project.Internal
    - Project.Libraries
    - Project.Types
executables:
  bookie:
    main: Main.hs
    source-dirs:  src
    ghc-options: -Wall
    dependencies:
      - optparse-generic


